insert into USERS(username,password,enabled) values ('dave','$2a$10$Ae1CML17.cAfSEpkqTU5Wunqg1TCHhJJ19.MwbWiuCXezQdNcQ1Ci',true);
insert into USERS(username,password,enabled) values ('zucka','$2a$10$Z95yJDb4eBZGPf3CZCsoNewW3I91pc6BFJyhmy/.iMvMAUQSrAV7m',true);

insert into AUTHORITIES(username,authority) values ('dave','USER');
insert into AUTHORITIES(username,authority) values ('zucka','USER');

insert into PEDIDO(nome_produto,valor_negociado,data_entrega,url_produto,url_imagem,descricao,status,username) values ('Dave Grohl - O Contador de Histórias: Memórias de Vida e Música',59.90,sysdate,'https://www.amazon.com.br/gp/product/6555605588/','https://m.media-amazon.com/images/P/B09N3ZR1F8.01._SCLZZZZZZZ_SX500_.jpg','Livro de memórias de Dave Grohl traz relato emocionante sobre a vida de um dos maiores nomes do rock internacional','APROVADO','dave');
insert into PEDIDO(nome_produto,valor_negociado,data_entrega,url_produto,url_imagem,descricao,status,username) values ('Uma verdade incômoda: Os bastidores do Facebook e sua batalha pela hegemoni',15.96,sysdate,'https://www.amazon.com.br/gp/product/B099FMQ8MY/','https://m.media-amazon.com/images/I/51N-RTRUp9S.jpg','O livro que o Facebook não quer que você leia. Uma reportagem explosiva sobre a busca irrefreável por crescimento e poder da rede social que mudou a forma como consumimos, votamos, pensamos e nos relacionamos.','PENDENTE','dave');
insert into PEDIDO(nome_produto,valor_negociado,data_entrega,url_produto,url_imagem,descricao,status,username) values ('Arrastados: Os bastidores do rompimento da barragem de Brumadinho, o maior desastre humanitário do Brasil',55.00,sysdate,'https://www.amazon.com.br/Arrastados-bastidores-rompimento-Brumadinho-humanit%C3%A1rio/dp/6555605642/','https://m.media-amazon.com/images/P/B09NF2YLNN.01._SCLZZZZZZZ_SX500_.jpg','Autora do best-seller Holocausto brasileiro lança o relato mais completo e emocionante sobre a tragédia em Brumadinho ocorrida em 2019.','ENTREGUE','zucka');
